### ISSUE TITLE
Segmentation fault during rt.putmask + groupby shift on an int column

### ISSUE THREAD

**Issue by zhangyingmath** [rtosholdings/riptable#111]
tmp1 = rt.Dataset({'f': [1,1,2,2], 'g': list('abcd'), 'h': [5,6,7,8]})

rt.putmask(tmp1['h'], tmp1.f == 1, tmp1.groupby(['f'])['h'].shift(-1))
(this gives me a segmentation fault)

**Comment by ykallus** [comment]
Presumably you want this instead?
`rt.putmask(tmp1['h'], tmp1.f == 1, tmp1.groupby(['f'])['h'].shift(-1)['h'])`

**Comment by zhangyingmath** [comment]
Yes, thanks @ykallus! That works and gives me what I wanted. 

I am still puzzled by why I had a seg fault (when I did sth wrong). It would be better to raise an error of some kind.

**Comment by staffantj** [comment]
This leaves an error for me.

From the command line:
`$ python -c 'import riptable as rt;tmp1 = rt.Dataset({'f': [1,1,2,2], 'g': list('abcd'), 'h': [5,6,7,8]});rt.putmask(tmp1['h'], tmp1.f == 1, tmp1.groupby(['f'])['h'].shift(-1))'
C:\ProgramData\Anaconda3\envs\riptide-dev39\lib\site-packages\llvmlite\binding\ffi.py:178: UserWarning: Module riptide_cpp was already imported from C:\ProgramData\Anaconda3\envs\riptide-dev39\lib\site-packages\riptide_cpp.cp39-win_amd64.pyd, but d:\src\repos\riptide_cpp is being added to sys.path
  from pkg_resources import resource_filename
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'f' is not defined`
From a source file:
`$ python ../../temp/segfault-111.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\riptide-dev39\lib\site-packages\riptable-1.3.1.post3+g3914cbf.d20220303-py3.9.egg\riptable\rt_numpy.py", line 2496, in putmask
    return a.putmask(mask, values)
AttributeError: 'FastArray' object has no attribute 'putmask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\src\temp\segfault-111.py", line 5, in <module>
    rt.putmask(tmp1['h'], tmp1.f == 1, tmp1.groupby(['f'])['h'].shift(-1))
  File "C:\ProgramData\Anaconda3\envs\riptide-dev39\lib\site-packages\riptable-1.3.1.post3+g3914cbf.d20220303-py3.9.egg\riptable\rt_numpy.py", line 2501, in putmask
    return np.putmask(a, mask, values)
  File "<__array_function__ internals>", line 5, in putmask
  File "C:\ProgramData\Anaconda3\envs\riptide-dev39\lib\site-packages\riptable-1.3.1.post3+g3914cbf.d20220303-py3.9.egg\riptable\rt_fastarray.py", line 2091, in __array_function__
    return self._legacy_array_function(func, types, args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\riptide-dev39\lib\site-packages\riptable-1.3.1.post3+g3914cbf.d20220303-py3.9.egg\riptable\rt_fastarray.py", line 2135, in _legacy_array_function
    return super(FastArray, self).__array_function__(func, types, args, kwargs)
ValueError: invalid literal for int() with base 10: 'h'`
